export type ObservingPoint =
  | 'didComposeMessage'
  | 'messageSent'
  | 'messageReceived'
  | 'messageRead'
  | 'didExecuteCommand'
  | 'willEmitUpdate'
  | 'didEmitUpdate'
  | 'participantJoined'
  | 'participantDeparted'
  | 'permissionResolved'
